# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zlx/peoplecounting/headdetection

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zlx/peoplecounting/headdetection

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zlx/peoplecounting/headdetection/CMakeFiles /home/zlx/peoplecounting/headdetection/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zlx/peoplecounting/headdetection/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vibe_test

# Build rule for target.
vibe_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vibe_test
.PHONY : vibe_test

# fast build rule for target.
vibe_test/fast:
	$(MAKE) -f CMakeFiles/vibe_test.dir/build.make CMakeFiles/vibe_test.dir/build
.PHONY : vibe_test/fast

#=============================================================================
# Target rules for targets named vibe

# Build rule for target.
vibe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vibe
.PHONY : vibe

# fast build rule for target.
vibe/fast:
	$(MAKE) -f CMakeFiles/vibe.dir/build.make CMakeFiles/vibe.dir/build
.PHONY : vibe/fast

ViBe/Vibe.o: ViBe/Vibe.cpp.o

.PHONY : ViBe/Vibe.o

# target to build an object file
ViBe/Vibe.cpp.o:
	$(MAKE) -f CMakeFiles/vibe.dir/build.make CMakeFiles/vibe.dir/ViBe/Vibe.cpp.o
.PHONY : ViBe/Vibe.cpp.o

ViBe/Vibe.i: ViBe/Vibe.cpp.i

.PHONY : ViBe/Vibe.i

# target to preprocess a source file
ViBe/Vibe.cpp.i:
	$(MAKE) -f CMakeFiles/vibe.dir/build.make CMakeFiles/vibe.dir/ViBe/Vibe.cpp.i
.PHONY : ViBe/Vibe.cpp.i

ViBe/Vibe.s: ViBe/Vibe.cpp.s

.PHONY : ViBe/Vibe.s

# target to generate assembly for a file
ViBe/Vibe.cpp.s:
	$(MAKE) -f CMakeFiles/vibe.dir/build.make CMakeFiles/vibe.dir/ViBe/Vibe.cpp.s
.PHONY : ViBe/Vibe.cpp.s

ViBe/main.o: ViBe/main.cpp.o

.PHONY : ViBe/main.o

# target to build an object file
ViBe/main.cpp.o:
	$(MAKE) -f CMakeFiles/vibe_test.dir/build.make CMakeFiles/vibe_test.dir/ViBe/main.cpp.o
.PHONY : ViBe/main.cpp.o

ViBe/main.i: ViBe/main.cpp.i

.PHONY : ViBe/main.i

# target to preprocess a source file
ViBe/main.cpp.i:
	$(MAKE) -f CMakeFiles/vibe_test.dir/build.make CMakeFiles/vibe_test.dir/ViBe/main.cpp.i
.PHONY : ViBe/main.cpp.i

ViBe/main.s: ViBe/main.cpp.s

.PHONY : ViBe/main.s

# target to generate assembly for a file
ViBe/main.cpp.s:
	$(MAKE) -f CMakeFiles/vibe_test.dir/build.make CMakeFiles/vibe_test.dir/ViBe/main.cpp.s
.PHONY : ViBe/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vibe_test"
	@echo "... vibe"
	@echo "... ViBe/Vibe.o"
	@echo "... ViBe/Vibe.i"
	@echo "... ViBe/Vibe.s"
	@echo "... ViBe/main.o"
	@echo "... ViBe/main.i"
	@echo "... ViBe/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

